### ISSUE TITLE
Migrate to WebPerf working group

### ISSUE THREAD

**Issue by dcreager** [w3c/reporting#100]
The Reporting spec has been adopted by the WebPerf working group, and included in its [proposed new charter](https://w3c.github.io/charter-webperf/).  This issue tracks moving the spec into the W3C repo (c.f. [this discussion](/WICG/network-error-logging/pull/82#discussion_r198623688) tracking a similar move for the NEL spec).

/cc @igrigorik @yoavweiss @plehegar @siusin @sideshowbarker 

[Intent to migrate](https://discourse.wicg.io/t/intent-to-migrate-reporting-and-network-error-logging/2864?u=dcreager) has already been filed in the WICG forum.

**Comment by igrigorik** [comment]
Do we need to update travis build? It doesn't seem like it's rebuilding gh-pages..

**Comment by dcreager** [comment]
It looks up to date now, I'm seeing the updates from #103 at https://w3c.github.io/reporting/

**Comment by igrigorik** [comment]
Ah, nice! Looks like the build takes a while? Either way, glad it's working.

**Comment by siusin** [comment]
Thank you @dcreager ! I've applied the WebPerf WG document license and the contributing policy to these two repos.

**Comment by dcreager** [comment]
And thank you!  I'll go ahead and close this; if we've missed anything in the transition, we can reopen.
