### ISSUE TITLE
Old spec URL does not forward to new one.

### ISSUE THREAD

**Issue by paulmeyer90** [w3c/reporting#102]
The old spec URL "https://wicg.github.io/reporting/" does not currently forward to the new/current URL "https://w3c.github.io/reporting/".

**Comment by igrigorik** [comment]
The "solution" for this is to recreate the WICG repo and setup a redirect in the gh-pages branch. 

Example: https://github.com/wicg/longtasks

**Comment by yoavweiss** [comment]
Done for both reporting and NEL
