### ISSUE TITLE
JFV reference

### ISSUE THREAD

**Issue by reschke** [w3c/reporting#107]
Should refer to:

https://greenbytes.de/tech/webdav/draft-reschke-http-jfv-09.html

**Comment by dcreager** [comment]
It looks like https://tools.ietf.org/html/draft-reschke-http-jfv-09 also works (and the [current link in specref](https://tools.ietf.org/html/draft-reschke-http-jfv) redirects there).  Do you have a preference for one over the other?

**Comment by reschke** [comment]
Ah, the site doesn't matter. Just use what's consistent with the use in the spec and the W3C.

**Comment by dcreager** [comment]
Done, thanks!
