### ISSUE TITLE
Clarify input to HTTP-JFV in "Parse reporting endpoint tuples from _value_"

### ISSUE THREAD

**Issue by juliatuttle** [w3c/reporting#12]
The "Parse reporting endpoint tuples from _value_" algorithm takes a string _value_ as input, and the first step is to run the instructions in section 4 of the HTTP-JFV spec. There are two problems with this as specified:
1. The spec does not specify that the input to the JFV subalgorithm is _value_.
2. If it did specify that, it would be a type error, because _value_ is a string but JFV expects a set of header values.

**Comment by clelland** [comment]
Note that this will be obsoleted if we accept #177

**Comment by clelland** [comment]
Closing; the header no longer uses HTTP-JFV.
