### ISSUE TITLE
ReportingObserver::observe() should be Promise-based

### ISSUE THREAD

**Issue by bakulf** [w3c/reporting#126]
Currently, observe() is a synchronous operation. In case the ReportingObserver is buffered, immediately after observe() should be possible to call takeRecords(), which should be able to get any pending record.

Is there a reason why observe() cannot be promise-based? And only when the promise is resolved, takeRecords() will be able to return the list of records.

**Comment by smaug----** [comment]
To keep the API using normal Observer pattern, I'd rather not make it return Promise, but just make observe()'s step 5 asynchronous, so that takeRecords() is guaranteed to return empty array right after observe() call.
