### ISSUE TITLE
Error in CSP header examples

### ISSUE THREAD

**Issue by AfroThundr3007730** [w3c/reporting#129]
In section 1.2, the CSP header in both examples have incorrect syntax:
> `Content-Security-Policy: ...; report-to=endpoint-1`

The syntax should be `report-to endpoint-1` instead of `report-to=endpoint-1`

Likewise for the second example:
> `Content-Security-Policy: ...; report-to=csp-endpoint`

The correct syntax would be `report-to csp-endpoint`

**Comment by dcreager** [comment]
Thanks very much for the report!  Updated the examples.
