### ISSUE TITLE
Format of dates

### ISSUE THREAD

**Issue by Martin-Pitt** [w3c/reporting#132]
Shouldn't the format of the date in [example 3 of 6.1 for the `anticipatedRemoval`](https://w3c.github.io/reporting/#deprecation-report) match the [ECMAScript's date interchange string format](https://tc39.github.io/ecma262/#sec-date-time-string-format) instead of depending on implementation-specific heuristics/formats?

I was really confused otherwise as to whether `1/1/2020` was one of those weird american dates where the month comes before the day and the year or if I could most definitely rely on this to be logical format. The ISO 8601 standard would be a lot better to rely on as examples (E.g. a date-only form is `YYYY-MM-DD`)

**Comment by dcreager** [comment]
Paul, can you take a look at this?  I think this is right, the example report should use `2020-01-01` since the field description already mandates ISO 8601.

**Comment by thafreeman** [comment]
I'm receiving reports with a JavaScript Date object (1552363200000). The example shows a date which is neither the Date object nor the ISO 8601 representation. This is really confusing.

**Comment by dcreager** [comment]
When you’re receiving a Date object, is that in a ReportingObserver, or in the JSON payload uploaded to a collector?  I think the former is supposed to receive a Date object; it’s only the latter that is supposed to be serialized as an ISO 8601 string.  @paulmeyer90 can correct me if I’m wrong.

**Comment by thafreeman** [comment]
I've received a Date object in a JSON payload from Chrome 70.0.3538 running on Windows:

`[{"age":52097,"body":{"anticipatedRemoval":1552363200000.0,"columnNumber":39,"id":"ElementCreateShadowRoot","lineNumber":425,"message":"Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.","sourceFile":""},"type":"deprecation","url":"","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"}]`

**Comment by paulmeyer90** [comment]
Do you think it would make sense to just define the |anticipatedRemoval| field as being a string (as YYYY-MM-DD format) in both ReportingObserver and JSON form?

**Comment by dcreager** [comment]
Are any of the other WebPerf APIs exposing dates or datetimes to JS code? If so we should mimic how they do it. I think it’s more important to have consistency in that direction than to have consistency between JS observers and the upload payload format.

/cc @igrigorik @yoavweiss

**Comment by clelland** [comment]
Discussed at TPAC; there aren't any other APIs in this space that use dates (as opposed to datetimes or timestamps). There was a suggestion to mimic HTTP, but that has a syntax based on RFCs 822 and 850, and is only used for timestamps in headers in any case. ("Sun, 06 Nov 1994 08:49:37 GMT", but also accepts "Sunday, 06-Nov-94 08:49:37 GMT" and "Sun Nov  6 08:49:37 1994", all with English identifiers and abbreviations)

I would suggest that we we use ISO8601 dates in YYYY-MM-DD format, as in https://github.com/w3c/reporting/issues/132#issuecomment-441695815)
