### ISSUE TITLE
Privacy concerns around Crash IDs.

### ISSUE THREAD

**Issue by paulmeyer90** [w3c/reporting#135]
There have been some privacy concerns raised regarding the Crash IDs contained in crash reports, during Chrome's privacy review of the feature. Some concerns can be seen on this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=898860#c8

**Comment by paulmeyer90** [comment]
I think because of these, I would like to remove Crash IDs for now. It hasn't yet been specced exactly what devs are supposed to do with these IDs anyways, so I don't think they make sense to keep at this point. They could always be reintroduced/redesigned in the future after shipping.

**Comment by igrigorik** [comment]
Resolved via #136.
