### ISSUE TITLE
Specify better data structures

### ISSUE THREAD

**Issue by juliatuttle** [w3c/reporting#14]
There are places in the spec where we specify a list, but then effectively use the data structure as a map or a set. For example:
1. Endpoint clients are a list, but making them a map from client origin to that client would make updates and deletes faster.
2. Cache endpoints are a list, but making them a map from endpoint URL to that endpoint would make updates and deletes faster.
3. Cache reports are a list, but making them a set would make random dequeues faster.

Using maps in cases 1 and 2 would also make it clearer that we only expect to have one endpoint per endpoint URL, and one client per (endpoint, origin).

**Comment by clelland** [comment]
Closing this as very stale; most of the infrstructure has been rewritten in terms of different data structures in the meantime, with the new reporting spec.
