### ISSUE TITLE
intervention reports do not contain id

### ISSUE THREAD

**Issue by thafreeman** [w3c/reporting#145]
I've noticed that the intervention reports I receive do not contain an id. Even though the documentation clearly states that this should be in the report. Even the example contains an id with a "audio-no-gesture" value. I was unable to find a list of valid id values as well.

https://w3c.github.io/reporting/#intervention-report

**Comment by paulmeyer90** [comment]
There isn't actually a list of valid ids. The only guarantee made by the id is that interventions of the same kind will have the same id, so the id can be used to uniquely track different interventions.

That being said, it should also be guaranteed that every intervention report contains an id field. I'll look into that.

**Comment by paulmeyer90** [comment]
This is now fixed in Chrome.
