### ISSUE TITLE
Relative URLs in endpoints configuration.

### ISSUE THREAD

**Issue by koto** [w3c/reporting#147]
Should the `Report-To` header allow for specifying relative URLs? That would allow the header value to be slightly smaller, e.g.:

```
Report-To: {"max_age":10886400,"endpoints":[{"url":"/reporting"}]}
```

IIUC, this would require only a small change in [Process reporting endpoints for response to request](https://www.w3.org/TR/reporting/#process-header), basically passing [response URL](https://fetch.spec.whatwg.org/#concept-response-url) as base URI to the URL parser.

**Comment by dcreager** [comment]
Interesting!  I hadn't considered this, because for NEL, you want your report collectors to be hosted somewhere different, so that you can (hopefully, possibly) still collect error reports when your users are having trouble reaching the monitored site.

But for something like CSP violations, that's less relevant, and I could see how you might want your collectors to just be another part of your main site.

/cc @igrigorik @yoavweiss Any strong feelings on this one?

**Comment by igrigorik** [comment]
Strong, "no". 

As precedent, CSP did allow relative URLs. @mikewest any words of wisdom or warning on that front?

**Comment by koto** [comment]
Ilya, could you expand a bit on why this is a strong "no"? 

To give some background to the issue, the domain name that the response will be served at may not always be known when some response headers are being generated (in general, it's somewhat useful for `Set-Cookie` headers only, and even ). In our case the CSP rollout uses relative URLs and report URI functionality for that reason - and it's simpler. 

This is, for example, the CSP for contacts.google.com regardless of which frontend server is being used:

```
content-security-policy: script-src 'report-sample' 'nonce-nonceval' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/ContactsUi/cspreport;worker-src 'self'
```

Additionally, for some setups it's not even possible to modify the response headers (e.g. serving static HTML files from multiple domains with the configuration in a set of `<meta http-equiv>` headers).

**Comment by igrigorik** [comment]
@koto oi, language fail.. That was meant to be read as "no, no strong objections". 

My only concern would be over the foot guns that this may expose.. I've seen enough people trip over relative paths to know that it can be an issue in practice. If we limit it to absolute paths, that makes things less error prone, but then will people complain about lack of relative paths? For what it's worth, these are not strong objections, but questions to consider.. I look at this request as an ergonomics question — nice to have, not must have — and I'd love to hear from folks that have production experience with this wild.

**Comment by koto** [comment]
Haha, sorry I read that wrong :)

FWIW I see some popular endpoints at Google use relative URLs as a CSP `report-uri` value. I don't have full context here, but I'm guessing simplicity of the header generation for multiple frontends played a role here, adding @arturjanc, maybe he knows. In our case, we require the authors to specify either an absolute URL, or a valid relative URL that starts with `/`, for most of endpoints this ends up being relative, possibly suggesting author's preference?

As a data point, we were *almost* switching to using CSP `report-to` for Trusted Types pilots, but the lack or relative URLs pushed us to report-uri, as much less refactoring was required for us to get this to work. 

One caveat I see is if you allowed non https:// reporting (such that reports might be sent over http://), but I believe that's not an issue anyway with the API.

**Comment by clelland** [comment]
I took a look at HTTPArchive data today to see what's being used in the wild for CSP reporting endpoints, at least those using report-uri in the header.

It appears to be split almost 50/50 between relative and absolute URLs (just looking for the presence of '://' in any tokens following the 'report-uri' directive.) 1121377 relative seen, 1010060 absolute.

Of the relative ones, only 4337 (0.3%) did *not* start with a "/" character, and a majority of those are misconfigurations.

**Comment by clelland** [comment]
I suspect that it may be easier for some sites to use absolute paths, especially in cases where identical configuration is used for multiple origins.

Imagining a case where a server is configured to respond and serve identical content from multiple hostnames; in that case, being able to configure the reporting header with an endpoint of "/report-endpoint.php" might be considerably easier than making the web server inject the origin into the header.

**Comment by koto** [comment]
For us, a middleware adds some headers, with identical values, for multiple applications hosted on different hostnames.

**Comment by yoavweiss** [comment]
OK, since there's usage in the wild and an actual use-case, maybe we should support relative URLs with absolute path. I'm wondering if we should *avoid* supporting relative paths, as they are likely to be a footgun, or we assume that folks just won't use them.

**Comment by clelland** [comment]
Relative paths are interesting -- they're a footgun for exactly the same set of folks who needed relative URLs, and who apply the same header to every resource.

On the other hand, they are well defined, and there's no reason that they won't work for document-scoped policies (using them for origin-scoped policies doesn't make any sense at all).

For now, I'll open up the grammar to allow [path-absolute-url-string](https://url.spec.whatwg.org/#path-absolute-url-string)s as well as absolute url strings.

**Comment by igrigorik** [comment]
@clelland thanks for digging into the data. 

> For now, I'll open up the grammar to allow [path-absolute-url-string](https://url.spec.whatwg.org/#path-absolute-url-string)s as well as absolute url strings.

👍

**Comment by eexit** [comment]
Hello, 

I was facing the same issue and found a workaround for Apache >= 2.4. Our stack makes use of the Apache wildcard so we have a single config that applies to all our apps. I wanted to also inject this header at the Apache level and not from our app.
I found a hacky way to build an absolute URL with Apache `Header` directive only:

```apache
Header set Report-To "{\"group\":\"csp-endpoint\",\"max_age\":10886400,\"endpoints\":[{\"url\":\"host/_/csp-report\"}]}"
Header edit Report-To "host" "%{REQUEST_SCHEME}e://%{HTTP_HOST}e"
```

Result:

```http
Report-To: {"group":"csp-endpoint","max_age":10886400,"endpoints":[{"url":"http://domain.test/_/csp-report"}]}
```

In this example, I'm doing it on my local Docker stack which does not run on HTTPS.

**Comment by Tengyyy** [comment]
I'm wondering if the new Reporting-Endpoints header that replaces Report-To allows for relative URLs or not?

**Comment by clelland** [comment]
It should -- [Process reporting endpoints for response](https://w3c.github.io/reporting/#process-header) specifies that the url should be resolved relative to the document's URL. (If you find that it doesn't, please file a bug with the relevant browser)
