### ISSUE TITLE
Add toJSON() method to Report and ReportBody

### ISSUE THREAD

**Issue by chrisguttandin** [w3c/reporting#164]
Hi everyone, I would like to suggest adding a `toJSON()` method to the Report and ReportBody interfaces.

I had the idea while I was trying to reimplement a method mentioned in this [article](https://developers.google.com/web/updates/2018/07/reportingobserver). The example code boils down to this:

```js
const observer = new ReportingObserver((reports) => {
  for (const report of reports) {
    sendReportToAnalytics(JSON.stringify(report.body));
  }
});
```

`sendReportToAnalytics()` is an imaginary function which sends the reports to some analytics service.

Unfortunately `JSON.stringify(report.body)` does only return an empty object in Chrome. I reckon this is because Chrome implemented all properties as getters. However I think the example above is a very common use case. Sending the reports to some server to further analyze them seems to me like the purpose of this API.

This is the reason why I would like to suggest adding a `toJSON()` method to the Report and the ReportBody. This function could then be invoked by `JSON.stringify` and would save web developers from implementing their own serialization logic.

Just for reference: The `RTCIceCandidate` and `RTCSessionDescription` of the WebRTC spec do have for example such a method as well.

https://www.w3.org/TR/webrtc/#dom-rtcicecandidate-tojson
https://www.w3.org/TR/webrtc/#dom-rtcsessiondescription-tojson

I haven't really followed the discussion around this API so far. Please feel free to close this issue if this has been discussed before or it seems to be unreasonable for other reasons.

**Comment by jpchase** [comment]
For the record there is an existing bug against the Chromium implementation: https://bugs.chromium.org/p/chromium/issues/detail?id=917945

There has been some investigation, but didn't find a fix. It may as suggested that the properties are implemented as getters.

Regardless, adding a toJSON() method is a good idea. I just wanted to also link up the bug.
