### ISSUE TITLE
"endpoints" is not defined as concept

### ISSUE THREAD

**Issue by annevk** [w3c/reporting#165]
There's numerous things that point to this as support for their own definition, but this really is a JSON object member only in the specification and has no real meaning?

**Comment by annevk** [comment]
It seems there is an "endpoint" concept. The problem is that your cross-references are going amiss.

**Comment by clelland** [comment]
Is this still an issue? "endpoint" is exported, and it looks like bikeshed's anchor database knows about it, and seems to link to the right section. `<a>endpoint</a>` appears to work.

`bikeshed refs --text=endpoint` gives me this now:

```
status:    current
for:       []
level:     1
url:       https://w3c.github.io/reporting/#endpoint
type:      dfn
export:    True
text:      endpoint
shortname: reporting
normative: True
spec:      reporting-1
```

Did you have example specs that pointed to the wrong place?

**Comment by annevk** [comment]
E.g., https://w3c.github.io/reporting/#guarantees points to https://w3c.github.io/reporting/#reportto-endpoints instead of https://w3c.github.io/reporting/#endpoint and there's a lot of that going on.
