### ISSUE TITLE
Privacy concerns with blacklist/whitelist

### ISSUE THREAD

**Issue by hillbrad** [w3c/reporting#19]
Do the blacklist/whitelist features allow re-identification of the user without informed consent?

If I call makeCredential() with a blacklist, is it clear to the user that the blacklist may reveal other identities they have registered with the site previously?

If I call getAssertion() with a whitelist, can't the timing of an immediate return if no credentials in that whitelist are present vs. a delay for user approval, also effectively re-identify a user without consent?

**Comment by igrigorik** [comment]
@hillbrad sanity check.. is this open against the right repo? :)

**Comment by hillbrad** [comment]
Aha, no, it is not!  The "please use GitHub issues" link in https://www.w3.org/TR/webauthn/ points here.  :/  Bikeshed copypasta.

**Comment by hillbrad** [comment]
(I've opened a new issue in the right repo requesting they fix their link)

**Comment by igrigorik** [comment]
👍
