### ISSUE TITLE
Privacy considerations should describe how user IDs can leak

### ISSUE THREAD

**Issue by jyasskin** [w3c/reporting#192]
Even after #186, a site that wants to tie a user ID into reports can probably do so. I see:

1. Define a unique reporting endpoint per user
2. Use the IP address the report comes from to limit the number of possible users.

There might be other mechanisms.

Browsers may want to take action to prevent this kind of identification, so it would be good to at least list the threats in the privacy considerations.

**Comment by clelland** [comment]
I've pushed up a PR that I think summarizes the important points.

I agree with you that "browsers may want to take action to prevent this kind of identification", but I'm not sure how to suggest that in the spec, other than calling out the specific hazards, and noting that they exist.

**Comment by jyasskin** [comment]
Looking back at this, I can't remember why I thought it was an issue. A site can choose to send information it knows to another server, and I think that's the only ability this bug is complaining about. Sorry for being confused and wasting your time.
