### ISSUE TITLE
Reporting-Endpoints processing

### ISSUE THREAD

**Issue by annevk** [w3c/reporting#199]
Why is this done for each response? Shouldn't this only be done for navigations and worker creation?

**Comment by clelland** [comment]
Good catch -- previously for network reporting, I think that the updated headers could take effect with any response, and would overwrite the stored endpoint configuration if there were changes. With document- (and worker-)only reporting, that should really just apply to responses for those resources.

**Comment by clelland** [comment]
(Also, this is probably the reason for the note "Fetch monkey patching. Talk to Anne" :) )

It probably makes more sense at this point to call that algorithm from  HTML's document initialization rather than in Fetch. WDYT?

**Comment by annevk** [comment]
Yeah + worker creation. All workers should register for their own reporting.

**Comment by clelland** [comment]
Closing this on the reporting side; #206 removes the processing from each report and exposes "Initialize a global's endpoint list" which can be called from HTML. The corresponding change to HTML is proposed in whatwg/html#5470.
