### ISSUE TITLE
grammar/content nit

### ISSUE THREAD

**Issue by dret** [w3c/reporting#2]
https://www.w3.org/TR/2016/WD-reporting-1-20160407/#header says "... to store a reporting endpoints for an origin."
maybe it was supposed to say: "to store a set of reporting endpoints"? but i am not quite sure what it was intended to say.

**Comment by dret** [comment]
or maybe it was intended to just say "to store reporting endpoints..."?

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/reporting/pull/3.
