### ISSUE TITLE
An editorial suggestion to simplify the "Process reporting endpoints for response" algorithm

### ISSUE THREAD

**Issue by triple-underscore** [w3c/reporting#201]
The step 2, 3 of section 3.3 [Process reporting endpoints for response](https://w3c.github.io/reporting/#process-header) states:

> 2. Let header be the value of the header in response’s header list whose name is "Reporting-Endpoints".
> 3. Let parsed header be the result of executing the algorithm defined in Section 4.2 of [STRUCTURED-HEADERS] on header, with header_type set to "dictionary". If that algorithm fails parsing, abort these steps.

The Fetch standard defines the "[get a structured header](https://fetch.spec.whatwg.org/#concept-header-list-get-structured-header)" algorithm for this purpose, and these steps can be rewritten as:

> 2. Let parsed header be get a structured header given "Reporting-Endpoints", "dictionary"
form response’s header list.
> 3. If parsed header is null or failure, then return.

Also, the second condition ("response’s header list does not contain... ) in the step 1 can also be removed by this (by checking null or not).

**Comment by clelland** [comment]
Nice catch, thanks!
