### ISSUE TITLE
Support for CSP Frame Ancestor violation reports

### ISSUE THREAD

**Issue by Bio2hazard** [w3c/reporting#203]
Hello,

what is the plan for supporting CSP Frame Ancestor reports?

We provide embeds for 3rd party sites to use and we use a frame-ancestors CSP on the embeds to filter out known bad actor / abusive 3rd party sites. Since we do not control these 3rd party sites, we have no control over what CSP policies or reporting endpoints they have in place.

With the ( for some reason already deprecated ) `report-uri` things work well - regardless of the 3rd party site's own CSP we receive reports when our embeds are blocked due to frame ancestors.

However, we were unable to get reports from frame-ancestors with `report-to`. We tested with the latest chrome version, and we confirmed that other types of CSP violations do work and submit the reports that we expect. 

Using chromes network capture and visualization tool, I can see that the reporting endpoint from the embed *is* added to the list of cached endpoints.

The best guess I have on why it's not working is because the violation is actually triggered on the origin of the 3rd party site, while the reporting endpoint is registered to our origin. That's just a guess, but matches the behavior we have seen.

Additionally, it would be great if we could receive the 3rd party origin in the report to our origin. To be clear, our motivation for this is not to track any user behavior, but rather to find false positives or frame ancestors that should be specified but that we missed. For example, a trusted partner or internal team might switch to a new CDN and neglect to inform us. If we knew the origin that caused the frame-ancestors violation we could resolve it on our end.

Thank you!

**Comment by clelland** [comment]
@mikewest 
I'm not sure, offhand, if this is an oversight / Chrome bug, or if there is a reason that these violation reports wouldn't be sent. I suspect the first, but Mike might know if there were privacy issues around reporting 3rd party behaviour here.

To be clear, you have a CSP on *your* site, which includes both the frame-ancestors and report_uri directives, and when *your* page is embedded by a third party, the report is not sent? Or am I misreading the issue?

**Comment by mikewest** [comment]
It might also be a bug in Chrome's implementation of `report-to`, which isn't substantially exercised as most usage is `report-uri`. I'd suggest filing a bug at https://crbug.com/new so we can diagnose.

**Comment by Bio2hazard** [comment]
Thank you, I will create a bug for chrome shortly.

@clelland that is correct.

Example:
Our embed lives at on https://thesite.com/embed.html and it returns 2 relevant headers:
`Report-To: { "group": "embedcsp", "max_age": 10886400, "endpoints": [{ "url": "https://reporting.com/csp" }], "include_subdomains": true}`
`Content-Security-Policy: frame-ancestors https://allowedsite.com ; report-uri https://reporting.com/csp; report-to embedcsp`

Then we have https://thirdparty.com that has a page that loads https://thesite.com/embed.html in an iframe, which results in a frame-ancestors violation.

We specified both because the main pages that come up when searching for CSP suggest specifying both ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri ):

>So for compatibility with current browsers while also adding forward compatibility when browsers get report-to support, you can specify both report-uri and report-to

With firefox and edge we received the CSP reports because they used the report-uri method.

With chrome, we get no reports at all. Ultimately we had to go against the advise to specify both and only specify report-uri.

I created the ticket here because I am not sure if this is a problem with chromes implementation or a problem with the reporting api spec itself, due to multiple origins being in play and the endpoints being resolved by origin.

Does that help?

**Comment by chlily1** [comment]
Looks like it's [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/csp/content_security_policy.cc;l=1209-1216;drc=34ad93361f96ad875bf350ced27e15b7aa126113?originalUrl=https:%2F%2Fcs.chromium.org%2F).

**Comment by Bio2hazard** [comment]
Hi @chlily1 - thank you, that looks promising!

It might be the section [just above your second link](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/csp/execution_context_csp_delegate.cc;l=183-188;drc=34ad93361f96ad875bf350ced27e15b7aa126113?originalUrl=https:%2F%2Fcs.chromium.org%2F) since in this case I assume `use_reporting_api` would evaluate to true.

That said it does seem like it would enqueue the report, so the actual issue might be elsewhere, but it is a good starting point for an investigation.

I created chrome bug report [1065150](https://crbug.com/1065150) for this issue 👍

**Comment by chlily1** [comment]
Ah yup. That's more likely. In which case it would come from around [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/csp/content_security_policy.cc;l=993-1001;drc=34ad93361f96ad875bf350ced27e15b7aa126113?originalUrl=https:%2F%2Fcs.chromium.org%2F).

**Comment by Bio2hazard** [comment]
Awesome 👍 And to clarify, using `chrome://net-export/` and the catapult netlog viewer shows that no reports were enqueued. 

![image](https://user-images.githubusercontent.com/2462038/77706837-b2885e80-6f80-11ea-9ba9-fbd28b23ee1b.png)

The green boxes obsfuscate the correct origin & reporting endpoint, the white one is unrelated. So it seems the reports either don't make it to the reporting API, or fail to be processed or something.

**Comment by clelland** [comment]
That helps a lot, thanks @Bio2hazard 

I'll take a look at that, it's definitely a bug in Chrome then.

**Comment by clelland** [comment]
And to address the original question, the plan is definitely to support these reports with the Reporting API.

The reporting configuration for CSP and other document-centric reports *is* changing: we will not be using cached reporting endpoint groups, but endpoints defined in a header returned with the same document as the CSP header. (If you currently issue both Report-To and CSP headers at the same time, this should be essentially no change, other than the syntax of the reporting header)

Whether or not we should include the origin of the embedding document is a separate issue; probably something to run by privacy folks. I suspect that exposing essentially the same information that you could get from the Referer header *should* be okay, but there may be more subtleties that I haven't considered.
