### ISSUE TITLE
Remove all references to ECMAScript global environment

### ISSUE THREAD

**Issue by domenic** [w3c/reporting#208]
This is an older term that has been obsoleted by "realm". (Indeed, all the links in the spec go to the definition of "realm"). But, probably you don't want to refer directly to realms either.

Probably any work here should happen after or as part of https://github.com/w3c/reporting/pull/206. In that case I would suggest changing everything to operate on `Document` (or `Window`) and `WorkerGlobalScope` objects directly, i.e. that's where you should put the "registered reporting observer list".

**Comment by clelland** [comment]
Makes sense; I think I was looking for a common base between Document and Worker execution contexts when I put that together. I'll move it as soon as I commit #206.

**Comment by clelland** [comment]
We could move **reports** and **endpoints** to the Document's or Worker's environment settings object. That interface is shared between them, so we wouldn't have to define `[=Document/reports=]` and `[=WorkerGlobalScope/reports=]` separately, and it's present even in a Document where scripting is disabled, which I think was my concern about using the global object directly.

**Comment by domenic** [comment]
Well, if you use environment settings object, then you also have to handle worklets...

**Comment by domenic** [comment]
There's no problem with using global objects in scripting-disabled documents.
