### ISSUE TITLE
Please fix the build

### ISSUE THREAD

**Issue by annevk** [w3c/reporting#213]
It seems that the latest commit did not build which means that the term queue is still not exported. And this means that a Fetch PR for COEP is blocked on this. Please help us :-)

cc @clelland

**Comment by clelland** [comment]
I'll take a look and see if it's anything I can fix.

**Comment by clelland** [comment]
Looks like it was a bikeshed issue, hopefully fixed by https://github.com/tabatkins/bikeshed/commit/40de15f959ec5d7a186f9ffd817b6857023e486e. I'll kick off another build.

**Comment by clelland** [comment]
Thanks for the heads-up -- it appears to be building again now, and *queue* now has `data-export` attached to the `dfn` node.

**Comment by annevk** [comment]
Great, thank you!
