### ISSUE TITLE
Is the definition of HTTP response header endpoints mandatory or can it be left out in the syntax?

### ISSUE THREAD

**Issue by piwowarczyk** [w3c/reporting#236]
Hi,

I found the following example on https://developers.google.com/web/updates/2020/05/heavy-ad-interventions#what_happens_when_an_ad_is_removed 

Report-To: { "url": "https://example.com/reports", "max_age": 86400 }

The syntax doesn't have the endpoints key while another example has them:

https://developers.google.com/web/updates/2018/09/reportingapi

Report-To: {
             "max_age": 10886400,
             "endpoints": [{
               "url": "https://analytics.provider.com/browser-errors"
             }]
           }

Is defining endpoints mandatory even if there is a single one or would the fist upper syntax work as well?

Thanks

Piotr

**Comment by clelland** [comment]
Hi @piwowarczyk --

The "endpoints" key was mandatory in the (now removed) JSON syntax. Even if just a single endpoint was defined in the group, the parser still expected an array of objects. The examples at https://www.w3.org/TR/reporting/ show this as well.

Note that the new `Reporting-Endpoints` removes this complexity, which is really only needed for Network Reporting. An equivalent header with the new syntax would be:

```
Reporting-Endpoints: default="https://example.com/reports"
```
