### ISSUE TITLE
The document in TR space hasn't been updated since 2018.

### ISSUE THREAD

**Issue by mikewest** [w3c/reporting#248]
Perhaps @sideshowbarker and friends can help set up auto-publication on this doc so that https://www.w3.org/TR/reporting/ matches https://w3c.github.io/reporting/?

**Comment by clelland** [comment]
Yes, please! I just fixed the pub script on this repo, but auto-publishing to TR, I think, should be the eventual goal.

**Comment by clelland** [comment]
See also #207

**Comment by samuelweiler** [comment]
Tagging @caribouW3 as the WebPerf team contact

**Comment by sideshowbarker** [comment]
> Perhaps @sideshowbarker and friends can help set up auto-publication on this doc so that [w3.org/TR/reporting](https://www.w3.org/TR/reporting/) matches [w3c.github.io/reporting](https://w3c.github.io/reporting/)?

Yeah, I’ll get it set up

**Comment by plehegar** [comment]
@caribouW3 did this.

**Comment by clelland** [comment]
Thanks!
