### ISSUE TITLE
OOM reporting in "crash" report

### ISSUE THREAD

**Issue by spanicker** [w3c/reporting#44]
Currently developers have little insight into implication of their memory footprint, in particular it would be great to consider exposing OOM as the reason for crashes (and potentially other coarse grain signals)
Is this inherently not possible via reporting API due to security reasons?
The explainer says that [crash report won't indicate any detail except unique ID due to security](https://github.com/WICG/reporting/blob/master/EXPLAINER.md#crashes)

**Comment by patrickkettner** [comment]
What is the request here - that we say something like `"reason": "oom"`?

**Comment by spanicker** [comment]
Yes.

**Comment by spanicker** [comment]
As an aside, in some of the crash cases the reporting might be very delayed, for instance if the browser process crashes and reports when its restarted, this should work if the max-age is sufficiently long?

**Comment by RByers** [comment]
I don't see any reason myself why we couldn't differentiate the crash type to at least separate browser bugs from OOMs.  Sounds like a good idea to me!

@juliatuttle do you persist reports to disk today?  I.e. would it even be reasonably possible for us to implement browser crash reporting?  I'm mainly concerned about renderer crash and OOM reporting, but @spanicker raises a good question.

**Comment by juliatuttle** [comment]
@RByers We don't persist reports to disk, but it's planned, since Chromium on Android in particular gets restarted pretty frequently.
