### ISSUE TITLE
Friendly TAG Review: Thoughts on the HTTP header

### ISSUE THREAD

**Issue by travisleithead** [w3c/reporting#53]
In response to https://github.com/w3ctag/design-reviews/issues/195

* JSON in the header... like it, but ensure it is encoded interoperably.
* URL for reporting--are the use cases for having fall-back URLs, in case of 404, or server-busy responses?

**Comment by RByers** [comment]
@mikewest I think these sound like questions for you?

**Comment by mikewest** [comment]
> JSON in the header... like it, but ensure it is encoded interoperably.

https://tools.ietf.org/html/draft-reschke-http-jfv-06 defines an interoperable format that I think we'd run with. It's not clear that the HTML WG actually likes that draft, but I do. /cc @reschke

> URL for reporting--are the use cases for having fall-back URLs, in case of 404, or server-busy responses?

I'm not really clear on the question, so:

1.  We allow multiple reporting groups to segregate reports by type for folks who do that sort of thing. You might have one set of endpoints for high-volume, high-noise CSP reports, and another for low-volume, high-signal reports like cert pinning violations, for instance.

2.  We do indeed allow groups to contain multiple servers in order to support load-balancing schemes and fallbacks. @igrigorik will have more practical detail than I do on this point, as I don't think I could tell you much more than that sentence. :)

**Comment by igrigorik** [comment]
As Mike noted, we allow multiple URLs to enable fallback/load-balancing, and there is a built-in back-off and retry mechanism in the processing section. A 404 would be treated as a delivery error, which would trigger delivery to a secondary URL, or trigger a back-off+retry for same URL.

**Comment by mikewest** [comment]
Since @travisleithead pinged this bug in https://github.com/w3ctag/design-reviews/issues/195, I'll note that the HTTP WG seems to have moved on to https://tools.ietf.org/html/draft-ietf-httpbis-header-structure, and seems to have rejected JSON (even though I still personally like it). Idunno. @mnot might have opinions.

**Comment by torgo** [comment]
Discussed this issue on our [TAG Call 5/8](https://github.com/w3ctag/meetings/blob/gh-pages/2018/telcons/05-08-agenda.md). We're a little concerned. Can we have a (friendly) discussion on a near future TAG call about this specific issue involving @mnot and @mikewest?

**Comment by mikewest** [comment]
I can join a (friendly) discussion. It would be better to pull in someone who's actually focusing time on this API as well, though: it's way off my radar at the moment. I just have opinions about header formats.

Basically: if we're all going to use structured headers for everything and the WG is totally happy with them, then this should use structured headers. If there's still debate on the topic, I like JSON more. @mnot (and @reschke?) will have more informed opinions on the topic than I do, as I imagine they're paying attention to it.

**Comment by dcreager** [comment]
> I can join a (friendly) discussion. It would be better to pull in someone who's actually focusing time on this API as well, though: it's way off my radar at the moment. I just have opinions about header formats.

Was there a resolution to this?  Are JSON headers still on the table as an option?  I've taken over the Chrome implementation from @juliatuttle so I have skin in the game.  :smile:

**Comment by dcreager** [comment]
> we allow multiple URLs to enable fallback/load-balancing, and there is a built-in back-off and retry mechanism in the processing section

Following up on this, #70 gives the server admin more explicit control over load balancing and failover, by adding optional `weight` and `priority` fields to each endpoint.

**Comment by mnot** [comment]
The HTTP WG has abandoned jfv in favour of structured headers, and SH is seeing adoption already in a number of specs.

That doesn't stop you from using JFV, of course. However, if a future version of HTTP has a more efficient encoding for SH, you wouldn't benefit from that.

**Comment by reschke** [comment]
> That doesn't stop you from using JFV, of course.

In which case we should consider publishing JFV as an informational spec.

**Comment by mnot** [comment]
We can discuss it, but I think it would be odd for the WG to publish two specs covering the same purpose. You could try on the independent stream, I guess, but conflict review might be interesting.

If it's just one spec, it could incorporate JFV.

**Comment by reschke** [comment]
Well, it doesn't need to be a WG spec. And we can make the intro explain things.

FWIW, inlining it in the other spec would be the wrong thing to do.

**Comment by dcreager** [comment]
> The HTTP WG has abandoned jfv in favour of structured headers, and SH is seeing adoption already in a number of specs.

Is there an explainer or appendix with examples of the syntax?  The SH spec draft focuses more on the grammar and parsing rules.  I'd like to flesh out a comparison of what the Reporting headers would look like in JSON vs SH.  My hunch is that SH will look nicer — no one has ever accused JSON of being easy to read...  :smile: 

The (to me, more important) flip side would be parsing.  Does SH have any open-source parsers yet?  When SH was first suggested ~2 years ago the thought was that by the time any specs were ready to use SH, there would be reusable parsers that we could use off the shelf, obviating one of JFV's benefits over SH.

**Comment by mnot** [comment]
@dcreager there are examples throughout [the spec](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html); if you find that lacking say so and we'll add more.

WRT parsers, we currently have [JavaScript](https://github.com/evert/structured-header) and the start of an implementation in [Chrome](https://cs.chromium.org/chromium/src/content/browser/web_package/signed_exchange_header_parser.cc?type=cs&q=StructuredHeader&sq=package:chromium&l=30) (for Web Packaging).

We're going to ship an updated draft in the next day or two and then do a wider call for implementations and feedback.

**Comment by travisleithead** [comment]
@mnot, can SH be nested? If not, that may be a non-starter for this feature...?

**Comment by hadleybeeman** [comment]
@mnot, how mature is this?  How many implementations do you have live already? (Just curious...)

**Comment by ylafon** [comment]
See also  httpwg/http-extensions#538

**Comment by mnot** [comment]
@travisleithead It can't. Assuming your're talking about Report-To](https://rbyers.github.io/reporting/#header), where is nesting needed? 

We're open to discussing new data structures if they seem likely to support a broad set of use cases.

@hadleybeeman as I said above, there's current a JavaScript implementation and a partial implementation in Google Chrome (for Web Packaging). The spec is starting to settle down some, so we're going to be encouraging more implementation soon.

**Comment by dcreager** [comment]
Re nesting — `Report-To` doesn't need *arbitrary* nesting, but it would be an array of maps, each of which contains an array of maps.  Latest draft of the header content is [here](https://wicg.github.io/reporting/#header).  An example in JSON would be:

``` http
Report-To: { "group": "csp-endpoint",
             "max_age": 10886400,
             "endpoints": [
               { "url": "https://example.com/csp-reports" }
             ] },
           { "group": "hpkp-endpoint",
             "max_age": 10886400,
             "endpoints": [
               { "url": "https://example.com/hpkp-reports" }
             ] }
```

**Comment by slightlyoff** [comment]
Thanks @dcreager!

Given that SH doesn't handle this well, can we all settle on moving forward with JSON here with the caveat that this spec should think harder about using JSON numbers (whose parsing and semantics are largely undefined)?

**Comment by dcreager** [comment]
SGTM

> this spec should think harder about using JSON numbers

Does TAG have any specific feedback here?  We're currently using numbers in the `Report-To` header for `max_age`, `endpoint.priority`, and `endpoint.weight`.  Those are all required to be integers.  We can add language that they must also be < 2^31, which should keep us outside of Here Be Dragons territory.

There's also @reschke's point about publishing JFV somewhere that we can cite, even if it includes an intro paragraph explaining that Structured Headers is now preferred where possible.

**Comment by dcreager** [comment]
> there's no reason to shove all report types into a single header field

I think we're on the same page here — the names in my example might have been misleading.  It's not the fact that the endpoint group is called `csp-endpoint` that would cause it to be used for CSP uploads; instead, there's a `report-to` field in the CSP header that references once of the named endpoint groups in `Report-To`.  Similarly for NEL, you'd have something like:

``` http
Report-To: { "group": "any-name-at-all",
             "max_age": 10886400,
             "endpoints": [
               { "url": "https://example.com/nel-reports" }
             ] }
NEL: {"report_to": "any-name-at-all", "max_age": 500}
```

You could reuse the same endpoint group for both CSP and NEL if you wanted to.

**Comment by dcreager** [comment]
#93 is now resolved; we need to keep the client-side load balancing and failover for NEL, and I've added some text in #94 to explain that if that logic turns out to be more generally useful, we can move it into (for instance) Fetch at some point.

That means we do need to keep the more nested structure for the `Report-To` field, and per @slightlyoff's earlier comment, that means we're still going to stick with JSON.
