### ISSUE TITLE
Friendly TAG Review: Crash ids

### ISSUE THREAD

**Issue by travisleithead** [w3c/reporting#55]
In response to https://github.com/w3ctag/design-reviews/issues/195

* The spec includes a notion of crash IDs - it would be worth mentioning that the uuids (or whatever ID mechanism) should *never* send any user identifiable information; noting that some UUID implementations (e.g. Windows) will [append system-level identifiers by default](https://blogs.msdn.microsoft.com/oldnewthing/20080627-00/?p=21823). These should not be inadvertant "supercookies" to stay in line with the [Unsanctioned Tracking Finding](https://www.w3.org/2001/tag/doc/unsanctioned-tracking/)

**Comment by RByers** [comment]
+1, thanks!

Filed #56 to track getting spec text written for the crash reports.

**Comment by paulmeyer90** [comment]
Crash IDs have been removed from the spec.
