### ISSUE TITLE
Define crash reports

### ISSUE THREAD

**Issue by RByers** [w3c/reporting#56]
We've heard from multiple developers (eg. @n8schloss for Facebook) that getting reports of browser crashes would be very valuable to them.  I mentioned it briefly in [the explainer](https://github.com/WICG/reporting/blob/master/EXPLAINER.md#crashes) but haven't thought about it much more.

@patrickkettner you said this was important for Edge, right? Do you want to take point on spec'ing this report type?

**Comment by patrickkettner** [comment]
Yep, i'll take a crack at this shortly

**Comment by paulmeyer90** [comment]
Crash reports are defined, so closing.
