### ISSUE TITLE
Use low priority task queue and add takeRecords to ReportingObserver?

### ISSUE THREAD

**Issue by RByers** [w3c/reporting#58]
@igrigorik [says](https://github.com/WICG/reporting/pull/47#discussion_r137701547) that we should probably queue tasks as low priority, eg. processed only during idle periods like [performance observer does](https://w3c.github.io/performance-timeline/#queue-a-performanceentry). Talking with @patrickkettner, I'm not sure that's the right tradeoff here. It increases the risk that reports will be missed (page navigates before observers invoked, etc.), and since reports are expected to be infrequent (no known scenario where there would be likely to have more than a couple dozen in a page lifetime) it seems like there would be little perf benefit.  But then maybe we'll want some future higher-frequency report scenario, and so it's better to design with this in mind?

If we do use a low priority task queue, then we definitely [need a takeRecords](https://github.com/WICG/reporting/pull/47#discussion_r137701088) method, like PerformanceObserver is [getting](https://github.com/w3c/performance-timeline/issues/74).   `takeRecords` would synchronously flush and returns the **report list** (eg. to be invoked in an unload handler).

Thoughts? @patrickkettner @mikewest

**Comment by patrickkettner** [comment]
-1 to the need for low priority queue - it makes sense for performance events but much less so for this.

**Comment by paulmeyer90** [comment]
I think it's fair to include a `takeRecords` method (good for consistency regardless).

I agree with others that a low priority queue is not warranted for ReportingObserver, as the number of reports generated in a page's lifetime is expected to be very limited.

**Comment by RByers** [comment]
[takeRecords](http://w3c.github.io/reporting/#dom-reportingobserver-takerecords) has landed in the spec, but we're still using generic "[queue a task](http://w3c.github.io/reporting/#add-report)" language. I think explicitly using a low-priority task queue is probably a good idea (we keep getting requests for larger volumes of reports, I doubt we can maintain the "number of reports generated in a page's lifetime is expected to be very limited" property for long).

**Comment by clelland** [comment]
"Queue a task" is in #220 now; closing this since the takeRecords issue was resolved.
