### ISSUE TITLE
Testing ReportingObserver in web platform tests.

### ISSUE THREAD

**Issue by paulmeyer90** [w3c/reporting#71]
It will be difficult to test the behavior of ReportingObserver in web platform tests without the ability to reliably generate reports. Since it would be difficult (and undesirable) to try to spec out specific deprecations or interventions that MUST generate reports (this will likely remain very implementation-specific), I'm thinking that it may be useful to spec out a way to generate specific custom reports. These custom reports would make testing very straightforward and reliable, and might also become a generally useful report type / use case on their own. For example, with certain ReportingObserver callbacks set up, a dev might want to generate custom reports in response to specific circumstances that they want to monitor, which will then trigger their observer callbacks in the same way as the browser-generated reports.

This could potentially be implemented as a CustomReport interface with at least a constructor that takes in a string message, and a send() method that sends the report. The sent report would have the "custom" type, and contain most of the fields of the proposed deprecation reports, including message, lineNumber, columnNumber, and sourceFile.

Thoughts?

**Comment by paulmeyer90** [comment]
@igrigorik @RByers

**Comment by patrickkettner** [comment]
Would it make sense to have the ability to trigger reports be in webdriver?

**Comment by RByers** [comment]
Yep, that's exactly what we just agreed with @foolip we'd look into ;-)​

**Comment by foolip** [comment]
@kereliuk to the rescue!

**Comment by kereliuk** [comment]
I think this could be done with a [WebDriver extension command](https://www.w3.org/TR/webdriver/#protocol-extensions)!

An existing example in a spec is [here](https://w3c.github.io/permissions/#automation)

> This could potentially be implemented as a CustomReport interface with at least a constructor that takes in a string message, and a send() method that sends the report. The sent report would have the "custom" type, and contain most of the fields of the proposed deprecation reports, including message, lineNumber, columnNumber, and sourceFile.

What does the string message that your constructor takes in represent?
There could have a WebDriver endpoint that invokes the send() method you are describing. WYT?

**Comment by paulmeyer90** [comment]
The string `message` will be contained in the generated report (as a string field named `message`).

I think WebDriver could work for testing purposes. Thanks for the suggestion!

That being said, I still wonder if custom reports could be a valuable addition to the reporting ecosystem; I will create a separate issue to discuss this.

**Comment by clelland** [comment]
@paulmeyer90, I know you were putting some work into this -- do you know if it was ever completed?

**Comment by jpchase** [comment]
This was completed. It required some spec changes to WebDriver and various plumbing for the Chrome implementation.

The Chromium tests are here:
https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/reporting/

The test results here:
https://wpt.fyi/results/reporting?label=master&label=experimental
