### ISSUE TITLE
Custom reports

### ISSUE THREAD

**Issue by paulmeyer90** [w3c/reporting#73]
Might it be useful to have a "custom" report type that would allow very general message-based reports to be generated? This would allow the existing Reporting API and ReportingObserver infrastructure to be leveraged beyond the confines of the predefined set of report types / events. For example, a dev may want an existing ReportingObserver callback to be called in additional but specific cases (with relevent information contained in the custom report), or collect additional information at the same endpoint defined via Reporting API header.

This could potentially be implemented as a "CustomReport" JS interface with at least a constructor that takes in a string message, and a send() method that sends the report. The sent report would have the "custom" type (I think it is important that this field not be changeable), and contain most of the fields of the proposed deprecation reports, including `message`, `lineNumber`, `columnNumber`, and `sourceFile`.

Thoughts?

**Comment by igrigorik** [comment]
Do we have particular examples of where and how this would be used? I'm somewhat reluctant to open this can of worms until we have concrete examples of why fetch() and sendBeacon() are not sufficient for these use cases.
